// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/11/2026, 4:23:16 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/damxey/Documents/Library Project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/damxey/Documents/Library Project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/damxey/Documents/Library Project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/damxey/Documents/Library Project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/damxey/Documents/Library Project/plugins/**/*.{js,ts,mjs}","/home/damxey/Documents/Library Project/composables/**/*.{js,ts,mjs}","/home/damxey/Documents/Library Project/utils/**/*.{js,ts,mjs}","/home/damxey/Documents/Library Project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/damxey/Documents/Library Project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/damxey/Documents/Library Project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/damxey/Documents/Library Project/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;